package io.server.content.achievement;

/**
 * @author <a href="http://www.rune-server.org/members/stand+up/">Stand Up</a>
 * @since 27-12-2016.
 */
public enum AchievementKey {
	VORKATH, COMPLETE_TUTORIAL, CHANGE_APPEARANCE, KILL_A_MAN, BURY_BONES, VOTE, SETUP_PRELOADING_GEAR, TRIVIABOT,
	HIGH_ALCHEMY, BARROWS, SKILL_MASTERY, EXPERIENCE_MASTERY, KILLER, WOODCUTTING, MINER, CRYSTAL_CHEST, GRIZZLY_BEAR,
	SHEAR_SHEEPS, STEAL_FROM_STALL, DAGGER, BOSSPOINT, HALL_OF_FAME, AGS_MAX, BALLISTA_MAX, MAULED, ENCHANT_BOLTS,
	BOSS_DESTROYER, BILLIONS, COMPLETE_RFD, KILL_KRAKEN, CUT_A_OAK_TREE, CATCH_A_SALMON, KILL_GALVEK, KILL_SKOTIZO,
	CRAFT_BLOODRUNE, CRAFT_DEATHRUNE, KILL_GLOD, TRIVIABOT_II, MINE_A_IRON_ORE, MINE_100_RUNITE_ORE, MINE_100_ORE,
	ZULRAHASS, KBDASS, KRAKENASS, CARCHASS, MITHDRAGASS, JADASS, WYVASS, ADEMONASS, STEELDRAGASS, SKELEWYVERN,
	FLETCH250ADAMANET, KILL_LAVA_DRAGON, DAGSASS, CUT_MAGICTREE, CUT_YEWTREE, CUT100TREES, BURN100YEW, BURN100ANY,
	COOK_A_SALMON, BURN_AN_OAK_LOG, POTION_MAKING, SECRETS_CHEST, SECRETS_CHEST_2, SECRETS_CHEST_3, SECRETS_CHEST_4
}
