package io.server.content.clanchannel.content;

/**
 * The clan task key set.
 *
 * @author Daniel
 */
public enum ClanTaskKey {
	/* Player Killing */
	PLAYER_KILLING, BOT_KILLING,



	/* Monster Killing */
	SAND_CRAB, HILL_GIANT, ROCK_CRAB, BLACK_DEMON, BLUE_DRAGON, GREEN_DRAGON, RED_DRAGON, BLACK_DRAGON, GREATER_DEMON,

	KING_BLACK_DRAGON, SCORPIA, CHAOS_ELEMENTAL, CHAOS_FANATIC, CRAZY_ARCHAEOLOGIST, CALLISTO, VENNANTIS,
	SKELETAL_WYVERN, ABYSSAL_DEMON,

	/* Skilling */
	THIEVING_STALL, CHOP_WILLOW_LOG, BURN_WILLOW_LOG, SHARK, DARK_CRAB, YEW_LOG, MAGIC_LOG, RUNITE_ORES,
	SUPER_COMBAT_POTION, SUPER_RESTORE_POTION, MAGIC_SHORTBOW, YEW_SHORTBOW, DEATH_RUNE, BLOOD_RUNE, AFK_LOG,
	CHOP_ANY_LOG, TRIVIA_ANSWER_KEY, COMPLETE_MASTERMINER_TASK_KEY, AGILITY_COURSE
}
