package io.server.content.activity.impl.duoinferno;

public final class DuoInfernoWaveData {

	/**
	 * 
	 * @author Adam_#6723
	 * Stores the NPC Data for Inferno
	 */
	public static final int 
	JAL_MEJRAH = 7692,  //ez
	JAL_AK = 7693,  //ez
	JAL_AKREK_MEJ = 7694, //ez
	JAL_AKREK_XIL = 7695, //ez
	JAL_AKREK_KET = 7696, //ez
    JAL_IMKOT = 7697,
    JAL_XIL = 7698,
	JAL_ZEK = 7699, 
	JALTOK_JAD = 7700,
	YT_HURKOT = 7705,
	TZKAL_ZUK = 7706, //last NPC.
	ANCESTRAL_GLYPH = 7707,
	JAL_MEJJAK = 7708;

	public static final int JAL_NIB = 7691;

	public static final WaveData DUOWAVE_2 = null;

	public static final WaveData DUOWAVE_1 = null;

	
	public enum WaveData {
		DUOWAVE_1(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH),
		DUOWAVE_2(JAL_NIB, JAL_NIB, JAL_NIB, JAL_MEJRAH, JAL_MEJRAH), 
		DUOWAVE_3(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB), 
		DUOWAVE_4(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK), 
		DUOWAVE_5(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH), 
		DUOWAVE_6(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_MEJRAH, JAL_MEJRAH), 
		DUOWAVE_7(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK),
		DUOWAVE_8(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB), 
		DUOWAVE_9(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT), 
		DUOWAVE_10(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH),
		DUOWAVE_11(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH), 
		DUOWAVE_12(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH), 
		DUOWAVE_13(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_AK),
		DUOWAVE_14(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK), 
		DUOWAVE_15(JAL_NIB, JAL_NIB, JAL_NIB, JAL_AK, JAL_AK, JAL_IMKOT), 
		DUOWAVE_16(JAL_NIB, JAL_NIB, JAL_NIB, JAL_IMKOT, JAL_IMKOT), 
		DUOWAVE_17(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB),
		DUOWAVE_18(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL), 
		DUOWAVE_19(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH), 
		DUOWAVE_20(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH), 
		DUOWAVE_21(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK), 
		DUOWAVE_22(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_MEJRAH),
		DUOWAVE_23(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_AK), 
		DUOWAVE_24(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK),
		DUOWAVE_25(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT),
		DUOWAVE_26(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH),
		DUOWAVE_27(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT), 
		DUOWAVE_28(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_AK), 
		DUOWAVE_29(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_IMKOT),
		DUOWAVE_30(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_MEJRAH, JAL_MEJRAH, JAL_AK),
		DUOWAVE_31(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_AK, JAL_AK, JAL_IMKOT),
		DUOWAVE_32(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_IMKOT, JAL_IMKOT),
		DUOWAVE_33(JAL_NIB, JAL_NIB, JAL_NIB, JAL_XIL, JAL_XIL),
		DUOWAVE_34(JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB, JAL_NIB),
		DUOWAVE_35(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK),
		DUOWAVE_36(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH),
		DUOWAVE_37(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH),
		DUOWAVE_38(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK),
		DUOWAVE_39(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_MEJRAH),
		DUOWAVE_40(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK),
		DUOWAVE_41(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK),
		DUOWAVE_42(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT),
		DUOWAVE_43(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_MEJRAH),
		DUOWAVE_44(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT),
		DUOWAVE_45(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_AK),
		DUOWAVE_46(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT),
		DUOWAVE_47(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT),
		DUOWAVE_48(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT),
		DUOWAVE_49(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT),
		DUOWAVE_50(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL),
		DUOWAVE_51(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL),
		DUOWAVE_52(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_MEJRAH, JAL_MEJRAH),
		DUOWAVE_53(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_AK),
		DUOWAVE_54(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_XIL, JAL_AK),
		DUOWAVE_55(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_XIL),
		DUOWAVE_56(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_XIL),
		DUOWAVE_57(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_IMKOT),
		DUOWAVE_58(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_IMKOT, JAL_XIL),
		DUOWAVE_59(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_IMKOT, JAL_XIL),
		DUOWAVE_60(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_IMKOT, JAL_XIL),
		DUOWAVE_61(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL),
		DUOWAVE_62(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_MEJRAH, JAL_MEJRAH, JAL_AK, JAL_IMKOT, JAL_XIL),
		DUOWAVE_63(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_AK, JAL_AK, JAL_IMKOT, JAL_XIL),
		DUOWAVE_64(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_IMKOT, JAL_IMKOT, JAL_XIL),
		DUOWAVE_65(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_XIL, JAL_XIL),
		DUOWAVE_66(JAL_NIB, JAL_NIB, JAL_NIB, JAL_ZEK, JAL_ZEK, JAL_ZEK),
		DUOWAVE_67(JALTOK_JAD),
		DUOWAVE_68(JALTOK_JAD,JALTOK_JAD,JALTOK_JAD),
		DUOWAVE_69(6506),
		;


		private final int[] monster;

		WaveData(int... monster) {
			this.monster = monster;
		}

		public int[] getMonster() {
			return monster;
		}

		public static WaveData getOrdinal(int ordinal) {
			for (WaveData wave : values()) {
				if (wave.ordinal() == ordinal)
					return wave;
			}
			return null;
		}

		public static WaveData getNext(int current) {
			return getOrdinal(current + 1);
		}
	}
}
